// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  product_grid: dynamic(() => import("./ProductGrid")),
  text_and_image: dynamic(() => import("./TextAndImage")),
  theme_grid: dynamic(() => import("./TeamGrid")),
  video_block: dynamic(() => import("./VideoBlock")),
};
